
services:

  kgrag-mcp-server-cpu:
    container_name: kgrag-mcp-server-cpu
    profiles:
      - cpu
    restart: always
    pull_policy: always
    image: ghcr.io/gzileni/kgrag-mcp-server:cpu
    ports:
      - "8000:8000"
      - "6379:6379"   # Redis
      - "6333:6333"   # QDrant
      - "6334:6334"   # QDrant
      - "7474:7474"   # HTTP - Neo4j
      - "7687:7687"   # Bolt - Neo4J
    expose:
      - "8000"
      - "6379"
      - "6333"
      - "6334"
      - "7474"
      - "7687"
    networks:
      - kgrag-mcp-network
    environment:
      - APP_ENV=${APP_ENV}
      - LLM_MODEL_TYPE=${LLM_MODEL_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - MODEL_EMBEDDING=${MODEL_EMBEDDING}
      - LLM_URL=${LLM_URL}
      - LOKI_URL=http://kgrag-mcp-loki:3100/loki/api/v1/push
    volumes:
      - qdrant_data:/qdrant/storage:z
      - redis_data:/data
      - neo4j_data:/var/lib/neo4j/data

  kgrag-mcp-server-gpu:
    container_name: kgrag-mcp-server-gpu
    profiles:
      - gpu
    restart: always
    pull_policy: always
    image: ghcr.io/gzileni/kgrag-mcp-server:gpu
    ports:
      - "8000:8000"
      - "6379:6379"   # Redis
      - "6333:6333"   # QDrant
      - "6334:6334"   # QDrant
      - "7474:7474"   # HTTP - Neo4j
      - "7687:7687"   # Bolt - Neo4J
    expose:
      - "8000"
      - "6379"
      - "6333"
      - "6334"
      - "7474"
      - "7687"
    networks:
      - kgrag-mcp-network
    environment:
      - APP_ENV=${APP_ENV}
      - LLM_MODEL_TYPE=${LLM_MODEL_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - MODEL_EMBEDDING=${MODEL_EMBEDDING}
      - LLM_URL=${LLM_URL}
      - LOKI_URL=http://kgrag-mcp-loki:3100/loki/api/v1/push
    volumes:
      - qdrant_data:/qdrant/storage:z
      - redis_data:/data
      - neo4j_data:/var/lib/neo4j/data

  kgrag-dev-cpu:
    container_name: kgrag-dev-cpu
    profiles:
      - dev
    restart: always
    image: ghcr.io/gzileni/memory-agent:cpu
    ports:
      - "6379:6379" # Redis
      - "6333:6333" # QDrant
      - "6334:6334" # QDrant
      - "7474:7474" # HTTP - Neo4j
      - "7687:7687" # Bolt - Neo4J
    expose:
      - "6379"
      - "6333"
      - "6334"
      - "7474"
      - "7687"
    networks:
      - kgrag-mcp-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - MODEL_EMBEDDING=${MODEL_EMBEDDING}
      - LLM_URL=${LLM_URL}
      - LOKI_URL=http://kgrag-mcp-loki:3100/loki/api/v1/push
    volumes:
      - qdrant_data:/qdrant/storage:z
      - redis_data:/data
      - neo4j_data:/var/lib/neo4j/data

  kgrag-mcp-loki:
    container_name: kgrag-mcp-loki
    profiles:
      - all
      - dev
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - kgrag-mcp-network

  kgrag-mcp-promtail:
    container_name: kgrag-mcp-promtail
    profiles:
      - all
      - dev
    image: grafana/promtail:latest
    volumes:
      - loki_log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - kgrag-mcp-network

  kgrag-mcp-grafana:
    container_name: kgrag-grafana
    profiles:
      - all
      - dev
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://kgrag-mcp-loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana  # Volume persistente per i dati di Grafana
    ports:
      - "3000:3000"
    networks:
      - kgrag-mcp-network

volumes:
  qdrant_data:
  redis_data:
  neo4j_data:
  grafana_data:
  loki_log:

networks:
  kgrag-mcp-network:
    name: kgrag-mcp-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24