
services:

  kgrag-mcp-server:
    container_name: kgrag_mcp_server
    restart: always
    image: ghcr.io/gzileni/kgrag_mcp_server
    ports:
      - "8000:8000"
    networks:
      - kgrag-network
    environment:
      - APP_ENV=${APP_ENV}
      - LLM_MODEL_TYPE=${LLM_MODEL_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - MODEL_EMBEDDING=${MODEL_EMBEDDING}
      - LLM_URL=${LLM_URL}
      - LOKI_URL=http://kgrag-mcp-loki:3100/loki/api/v1/push

  kgrag-mcp-loki:
    container_name: kgrag-mcp-loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - kgrag-network

  kgrag-mcp-promtail:
    container_name: kgrag-mcp-promtail
    image: grafana/promtail:latest
    volumes:
      - loki-log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - kgrag-network

  kgrag-mcp-grafana:
    container_name: kgrag-grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://kgrag-mcp-loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana  # Volume persistente per i dati di Grafana
    ports:
      - "3000:3000"
    networks:
      - kgrag-mcp-network

networks:
  kgrag-mcp-network:
    name: kgrag-mcp-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24